project_id = "phlhbbjeqabjhkkyennz"

[functions.cleanup-events]
verify_jwt = false

[functions.get-external-events]
verify_jwt = false

[functions.get-ticketmaster-events]
verify_jwt = false

[functions.generate-event-summaries]
verify_jwt = false

[functions.sync-ticketmaster-events]
verify_jwt = false

[functions.generate-ai-descriptions]
verify_jwt = false

[functions.upload-assets]
verify_jwt = false
